spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:hack
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  clova:
    api:
      url: ${CLOVA_CHAT}
      api_gateway_key: ${API_GATEWAY_KEY}
      api_key: ${API_KEY}

    sql:
      init:
        mode: always
  data:
    redis:
      port: 6379
      host: localhost

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      ssl:
#        enabled: true
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

